
[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[window]
opacity = 1.0
# decorations = "none"
padding = { x = 15, y = 15 }

[general]
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]
